#!/bin/bash

ROOT_CFG="/root/.config/rustdesk/RustDesk2.toml"
SOCKS_PORT=1080
RD_PASSWORD=""
RD_IP=""
SSH_CLIENT_IP=""
SSH_SERVER_IP=""
RUNTIME_FILE="/dev/shm/lliurex-rdesk"
# main function
main(){
	[ "$1" ] || usage
	ACTION="$1"
	shift
	case "$ACTION" in
		configure|enable)
			root_test || die "You must be root to run this program"
			if ! test_rustdesk_installation ; then
				if ! install_rustdesk ; then
					die "Rustkdesk installation failed. Exitting"
				fi
			fi

			CONN_PASS="$(gen_password)"
			enable_connection "$CONN_PASS"
			get_ssh_ip

			echo "Configuration completed"
			echo "Connection is allowed ONLY if remote user opens RustDesk window"
			echo "*****************************"
			echo ">IP: $SSH_SERVER_IP"
			echo ">PASSWORD: $CONN_PASS"
			echo "*****************************"
			echo ""
		        echo "Run locally this COMMAND to connect to remote system:"
			echo ""
			echo "lliurex-rdesk connect $SSH_SERVER_IP"
			echo ""
			echo ""
			;;

		menu)
			RDESK_CMD="$0"
			a=""
			TIMEOUT="1.5"
			n=0
			show_menu
			while [ "$a" != "0" ] ; do
				if [ $n -eq 1 ] ; then
					CHR=" "
					n=0
				else
					CHR="_"
					n=1
				fi

				printf "\r$CHR"
				read -t $TIMEOUT a
				printf " \b"
				case "$a" in
					1)
						TMP_FILE="$(mktemp)"
						run_with_sudo $RDESK_CMD configure |tee "$TMP_FILE"
						RD_PASSWORD="$(parse_value ">PASSWORD" "$TMP_FILE")"
						RD_IP="$(parse_value ">IP" "$TMP_FILE")"
						rm -f "$TMP_FILE"
						;;

					2) 
						run_with_sudo $RDESK_CMD disable
						;;

					3)
						loginctl list-sessions
						echo "(To unlock, use command 'sudo loginctl unlock-session {ID})')"
						;;

					8)
						show_menu
						;;
					9)
						/bin/bash
						# bash --rcfile /tmp/bashrc 
						;;
					0)
						run_with_sudo $RDESK_CMD disable
						echo "Program terminated. Now is safe to use [CTRL] C if required"
						exit 0
						;;
				esac
			done
			;;

		disable)
			root_test || die "You must be root to run this program"
			disable_connection
			;;

		remote-menu)
	        	REMOTE_USER=""
		        REMOTE_IP=""
			if [ "$1" ] && echo "$1" |grep -q '@' ; then
		        	REMOTE_USER="${1%@*}"
			        REMOTE_IP="${1#*@}"
			fi
			if [ -z "$REMOTE_USER" ] || [ -z "$REMOTE_IP" ] ; then
				die "You must specify remote USER@IP_ADDRESS"
			fi
			runtime_write "RD_IP" "$REMOTE_IP"
			CMD_OPTION="menu"
			launch_socks_tunnel "$REMOTE_USER" "$REMOTE_IP" "$CMD_OPTION"
			;;

		create-tunnel)
			root_test || die "You must be root to run this program"
	        	REMOTE_USER=""
		        REMOTE_IP=""
			if [ "$1" ] && echo "$1" |grep -q '@' ; then
		        	REMOTE_USER="${1%@*}"
			        REMOTE_IP="${1#*@}"
			fi
			if [ -z "$REMOTE_USER" ] || [ -z "$REMOTE_IP" ] ; then
				die "You must specify remote USER@IP_ADDRESS"
			fi
			TUN_IP="$(gen_net_ip)"
			echo "***********************************"
			echo "Access remote host with command:"
			echo ""
			echo "$0 connect $TUN_IP"
			echo ""
			echo "***********************************"
			launch_tunnel  "$REMOTE_USER" "$REMOTE_IP" "$TUN_IP"
			;;

		connect)
			if [ "$1" ] ; then
				REMOTE_IP="$1"
			else
				REMOTE_IP="$(runtime_read "RD_IP")"
			fi
			[ "$REMOTE_IP" ] || die "Unable to determine remote IP_ADDRESS, please specify in command line"
			if root_test ; then
				die "You must run this progran as NON root user"
			fi
		        REMOTE_IP="${1}"
			launch_rustdesk "$REMOTE_IP"
			;;
		info)
			show_local_info
			;;

		*)
			usage
			;;
	esac
	exit 0

}


usage(){
        die "Usage" "$(basename "$0") {enable | disable | configure | menu | info}" \
            "       $(basename "$0") remote-enable {USER@REMOTE_IP}" \
            "       $(basename "$0") remote-menu {USER@REMOTE_IP}" \
            "       $(basename "$0") connect [REMOTE_IP]" \
            "       $(basename "$0") create-tunnel {USER@REMOTE_IP}"
}

die(){
        TYPE="ERROR"
        if [ "$#" -gt 1 ] ; then
                TYPE="$1"
                shift
        fi
        printf "${TYPE}: " >&2
        while [ "$1" ] ; do
                echo "$1" >&2
                shift
        done
        echo "" >&2

        exit 1
}

show_menu(){
	clear
	get_ssh_ip
	cat <<EOF
*******************************************
* RDESK CONSOLE
* CONNECTED AS: $USER@$SSH_SERVER_IP
*         FROM: $SSH_CLIENT_IP
*******************************************

HOST INFO
--------------------------------
EOF
	show_local_info
	echo -e "\nRUSTDESK INFO"
	echo "--------------------------------"
	show_rustdesk_info
	cat <<EOF

********************************
* RDESK OPTIONS MENU
********************************
1 Enable access (sudo required)
2 Disable access (sudo required)
3 List current sessions
--------------------------------
8 Refresh info
9 Run local shell
0 Exit
--------------------------------

EOF
}

get_ssh_ip(){
	SSH_CLIENT_IP="$(echo "$SSH_CONNECTION" |cut -f 1 -d ' ')"
	SSH_SERVER_IP="$(echo "$SSH_CONNECTION" |cut -f 3 -d ' ')"
}

get_ip(){
	# get first default route iface name
	GW_IFACE="$(LANG=C ip -4 route list 0/0 |head -1 |cut -d ' ' -f 5)"
	# print IP of GW_IFACE
	LANG=C ip a show dev "$GW_IFACE" |sed -ne "/^\s*inet\s/{s%^\s*inet\s*%%;s%/.*$%%;p}"
}

show_local_info(){
	cat <<EOF
HOST_NAME: $(hostname -f)
HOST_IP_ADDRESS:  $(get_ip)
HOST_VERSION: $(lliurex-version)
HOST_TAGS: $(lliurex-version -g --tag-prefix '           ' |sed -e "1s%^\s*%HOST_TAGS: %")
EOF
}

show_rustdesk_info(){
	RD_VERSION="$(LANG=C dpkg -l rustdesk |tail -1 |sed -e "s%\s\+%\t%g" |cut -f 3)"
	RD_STATUS="ENABLED"
	check_connection || RD_STATUS="DISABLED"
	RD_WINDOW="Y"
	ps -ef |grep -q "/usr/bin/rustdesk$" || RD_WINDOW="N"

cat <<EOF
RUSTDESK_VERSION: $RD_VERSION
RUSTDESK_ACCESS_STATUS: $RD_STATUS
RUSTDESK_PASSWORD: $RD_PASSWORD
RUSTDESK_WINDOW_DETECTED: $RD_WINDOW
EOF
}

parse_value(){
	KEY="$1"
	FILE="$2"
	sed -ne "/^$KEY:/{s%^.*:\s*%%;p}"
}

runtime_read(){
	KEY="$1"
	parse_value "$KEY" "$RUNTIME_FILE"
}

runtime_delete(){
	KEY="$1"
	sed -i -e "/^${KEY}:/d" "$RUNTIME_FILE"
}

runtime_write(){
	KEY="$1"
	VALUE="$2"
	runtime_delete "$KEY"
	echo "$KEY: $VALUE" >> "$RUNTIME_FILE"
}

run_with_sudo(){
	sudo --preserve-env=SSH_CONNECTION "$@"
}


root_test(){
	[ $(id -u) -eq 0 ] || return 1
	return 0
}

test_rustdesk_installation(){
	PKG_NAME="rustdesk"
	dpkg -l "$PKG_NAME" >/dev/null 2>/dev/null || return 1
	return 0
}

install_rustdesk(){
	RUSTDESK_URL="https://github.com/rustdesk/rustdesk/releases/download/1.4.6/rustdesk-1.4.6-x86_64.deb"
	TMP_DIR="$(mktemp -d)"
	DEST_FILE="$TMP_DIR/rustdesk.deb"
	wget -O "$DEST_FILE" "$RUSTDESK_URL"
	rc=1
	echo "$DEST_FILE"
	ls -al "$DEST_FILE"

	if [ -s "$DEST_FILE" ] ; then
              rc=0
	      apt install -y "$DEST_FILE" || rc=$?
	fi
	rm -fr "$TMP_DIR"
	return $rc
}

gen_password(){
	tr -dc A-Za-z0-9 </dev/urandom | head -c 8
	echo ""
}

gen_net_address(){
	echo "10.10.10.1/24"
}

gen_net_ip(){
	gen_net_address |cut -f 1 -d "/"
}

create_net_alias(){
	NET_ADDRESS="$(gen_net_address)"
	ip a add "$NET_ADDRESS" dev lo
}

delete_net_alias(){
	NET_ADDRESS="$(gen_net_address)"
	ip a del "$NET_ADDRESS" dev lo
}

enable_connection(){
	CONN_PASS="$1"
	# configure rustdesk

	# enable lan access
	rustdesk --option direct-server Y

	# disable remote server
	rustdesk --config 'host=localhost'

	# set random password
	RND_PASS="$(gen_password)"
	rustdesk --password "$CONN_PASS"

	# disable connection if rustdesk window is closed
	rustdesk --option allow-only-conn-window-open Y


	# configure network alias
	# create_net_alias
	echo "Configuration enabled"
}



disable_connection(){
	# configure rustdesk

	# disable lan access
	rustdesk --option direct-server N

	# disable remote server
	rustdesk --config 'host=localhost'

	# disable password
	rustdesk --password ''

	# remove network alias
	
	#delete_net_alias
	echo "Configuration disabled"
}

check_connection(){
	# check status of 'direct-server' option
	# to guess if rustdesk is configured
	# for remote access
	rustdesk --option direct-server |grep -q "Y" || return 1
	return 0
}

launch_rustdesk(){
	REMOTE_IP="$1"
	rustdesk --connect "$REMOTE_IP"
}

tproxy_disable(){
	echo "Removing TPROXY settings"
	ip route del local default dev lo table 100
	ip rule del fwmark 1 lookup 100
}

tproxy_enable(){
	tproxy_disable
	echo "Adding TPROXY settings"
	ip route add local default dev lo table 100
	ip rule add fwmark 1 lookup 100
}

cfg_get_section(){
	SEC_NAME='.*'
	if [ "$1" ] ; then
		SEC_NAME="$1"
	fi
	grep -n  "^\[${SEC_NAME}\]$" "$ROOT_CFG" |cut -f1 -d ':'
}

cfg_sections_from_line(){
	BEGIN_LINE="$1"
	cfg_get_section |while read l; do
		if [ $l -gt $BEGIN_LINE ] ; then
			echo "$l"
		fi
	done
}

cfg_backup(){
	TIME_STAMP="$(date +%s)"
	cp "$ROOT_CFG" "${ROOT_CFG}.${TIME_STAMP}"
}


socks5_enable(){
	# TODO: find a better way to configure this settings ...
	FIRST_LINE="$(cfg_get_section "socks")"
	if [ "$FIRST_LINE" ]; then
		LAST_LINE='$'
		# get next section line number
		NEXT_LINE="$(cfg_sections_from_line $FIRST_LINE |head -1)"
		if [ "$NEXT_LINE" ]; then
			LAST_LINE=$(($NEXT_LINE -1))
		fi
		cfg_backup
		# remove section
		sed -i -e "$FIRST_LINE,${LAST_LINE}D" "$ROOT_CFG"
	fi
	# create new section
	cat <<EOF >> "$ROOT_CFG"

[socks]
proxy = 'socks5://localhost:$SOCKS_PORT'
username = ''
password = ''

EOF
	# restart service
	RUSTDESK_SERVICE="rustdesk"
	systemctl restart "$RUSTDESK_SERVICE"

}

launch_tunnel(){
	launch_socks_tunnel "$@"
}

launch_socks_tunnel(){
	REMOTE_USER="$1"
	REMOTE_IP="$2"
	OPTION_CMD="$3"
	CMD_BASE="/home/admingva/lliurex-rdesk/lliurex-rdesk"
	case "$OPTION_CMD" in
		enable)
			REMOTE_CMD="sudo --preserve-env=SSH_CONNECTION $CMD_BASE enable"
			;;
		menu)
			REMOTE_CMD="$CMD_BASE menu"
			;;
	esac

	ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -D $SOCKS_PORT ${REMOTE_USER}@${REMOTE_IP} $REMOTE_CMD
}

launch_sshuttle_tunnel(){
	REMOTE_USER="$1"
	REMOTE_IP="$2"
        TUN_IP="$3"
	tproxy_enable
	sshuttle -vr ${REMOTE_USER}@${REMOTE_IP} $TUN_IP --method tproxy --ssh-cmd 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' || true
	tproxy_disable
}

main "$@"
	

