# Lliurex RDesk
Luis Garcia
:compat-mode:
:toc:
:icons: font
:toc-title: Index
:toclevels: 3
:doctype: article
:experimental:
:icons: font
:sectanchors:
:sectlinks:
:sectnums:
:imagesdir: ./images

## LliureX RDesk

image::lliurex-rdesk.svg[height=80]

Simple remote desktop control based on RustDesk with Wayland support and using just a single ssh connection to create a tunnel without any firewall configurations or hosting a server.

## Context
**Wayland** is now the default display server in most of the actual linux distributions, including LliureX 25 (Based on Ubuntu 24.04).
Most of the remote desktop control solutions that work on X11, fail on Wayland, therefore, for the deployment of Lliurex 25, it was essential to have a tool capable of providing remote support for computers running Wayland.

The DGIE provides the educational community with IT and equipment support services (SAI/SILO). Until now, the selected tool for remote desktop assistance in Windows and previous versions of LliureX was **AnyDesk , but, unfortunately, this aplication is not compatible with Wayland.**

To solve this problem, the LliureX development team has implemented a remote access solution based on **RustDesk**. RustDesk is a multifeatured remote desktop application written in rust with (experminental) support for Wayland. 

## Concepts
In this context of remote management, we will use the terms of:

- **'manager'** and 'manager host' to refer to the technician and the computer used to take control over a managed device in an educational centre
- **'client'** and 'client host' for the managed remote system user and computer respectively

image::concepts.svg[]

LliureX RDesk requires a **direct connection** from the manager to the remote client host **without needing any intermediate RustDesk server**. It **uses a single ssh connection to create a tunnel (proxy socks)** and configure RustDesk appropriately at each end to use the tunnel, so ONLY ssh port (22 TCP) is needed. LliureX RDesk manages **all the required comunications between manager and client over the ssh tunnel.**

The access to the remote client is not transparent and **can NOT be operated in a full unattended way**. The remote user must activate the software (rustdesk) in a conscious way to allow and accept the manager access. The user can also terminate connection at any time.

## Packages

- **lliurex-rdesk-manager**: provides configuration and tools for manager host
- **lliurex-rdesk-client**: required package for client devices
- **lliurex-rdesk-common**: common stuff. It's a required dependency of manager and client packages

## Quick start

### Client device
Just install lliurex-rdesk-client package to get dependeincies and RustDesk configuration:
```
sudo apt install lliurex-rdesk-client
```
The client RustDesk configuration is done from the manager, so that's all in client side.

> [NOTE]
> This occurs only during the very first installation of the package, subsequent updates do not change the client configuration.

To allow access, client user must run 'lliurex-rdesk-allow-access' from a terminal or application menu image:lliurex-rdesk-allow-access.svg[height=40]

### Manager computer

#### Install lliurex-rdesk-manager package:
```
sudo apt install lliurex-rdesk-manager
```

In order to get control over a remote client, you need:

- IP address of client
- Login credentials to access client via ssh. In addidition, **administrative privileges (sudo)** are required to enable remote control in the client.

#### Run 'lliurex-rdesk-manager-console' to access the remote client. You can supply the user and the host address in command line:

```
lliurex-rdesk-manager-console USER@REMOTE_IP
```

If no arguments are provided, you will be asked to enter data nteractively.
This utility is also available in the applications menu. image:lliurex-rdesk-manager-console.svg[height=40]

The program require you to enter password for ssh connection. After login, the basic information of the host and an old-fashioned tty menu will be shown in terminal:

```
*******************************************
* RDESK CONSOLE
* CONNECTED AS: <USER>@1<HOST>
*         FROM: <MANAGER_HOST>
*******************************************

HOST INFO
---------
HOST_NAME: <HOSTNAME>
HOST_IP_ADDRESS:  <IP_ADDRESS>

LLIUREX INFO
------------
HOST_VERSION: ...
HOST_TAGS: ...

RUSTDESK INFO
-------------
RUSTDESK_VERSION: <VERSION>
RUSTDESK_ACCESS_STATUS: ?????
RUSTDESK_PASSWORD: ?????
RUSTDESK_WINDOW_DETECTED: N

********************************
* RDESK OPTIONS MENU
********************************
1 Enable access (sudo required)
2 Disable access (sudo required)
3 List current sessions
--------------------------------
8 Refresh info
9 Run local shell
0 Exit
--------------------------------

```

#### Press 1 to enable remote access.

This command configures RustDesk client and generates a temporary password. The password will be shown in screen.

#### Run 'lliurex-rdesk-manager-desktop' in a separate terminal or from applications menú.

image::lliurex-rdesk-manager-desktop.svg[height=40]

## Usage

### lliurex-rdesk
```
Usage: lliurex-rdesk {enable | disable | local-console | info | popup | allow-access}
       lliurex-rdesk {socks-enable | socks-disable} [OPTIONS]
       lliurex-rdesk remote-console {USER@REMOTE_IP}
       lliurex-rdesk desktop [REMOTE_IP]
       lliurex-rdesk create-tunnel {USER@REMOTE_IP}
```


