[Service]
# rustdesk does not create pid file for the service, but 
# presence of this file is required to run ExecStartPost actions
# This code provides the file if not already present
ExecStartPost=/bin/sh -c "[ -e /var/run/rustdesk.pid ] || pgrep -of 'rustdesk --service' >/var/run/rustdesk.pid"

ExecStartPost=echo POST
ExecStartPost=-/bin/sh -c "sleep 4 && /usr/bin/pkill -f 'rustdesk --tray'"
